apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  labels:
    "operatorframework.io/arch.amd64": supported
    "operatorframework.io/arch.ppc64le": supported
    "operatorframework.io/arch.s390x": supported
    "operatorframework.io/arch.arm64": supported
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cache.openshifttest/v1alpha1",
          "kind": "Sample",
          "metadata": {
            "name": "example",
            "namespace": "default"
          },
          "spec": {
            "name": "example",
            "namespace": "default"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.16.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: sample-operator.v0.1.4
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Sample is the Schema for the samples API
      displayName: Sample
      kind: Sample
      name: samples.cache.openshifttest
      version: v1alpha1
  description: Sample operator
  displayName: Sample operator
  icon:
  - base64data: /9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUVFRgVFhYYGBgYGBgYGBgZGRgYGBgaGRgaGRgYGhgcIS4lHB4rHxgYJzgmKy80NTU1GiU7QDs0Py40NTEBDAwMEA8QHhISHjEjJCs0NDQ0NDE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0PzQ0NDQ0NDQ0MTQ0NDQ0NP/AABEIAOEA4AMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAAAQIDBAUGB//EAEEQAAIBAgMEBgkBBQYHAAAAAAECAAMRBBIhBTFBUQYiYXGBkRMyQlKhscHR8BQHIzNi4SRygpKy8RUWNGODlML/xAAaAQACAwEBAAAAAAAAAAAAAAAAAgEDBAUG/8QAJxEAAwACAQQCAgIDAQAAAAAAAAECAxEhBBIxQRNRFCIyYQVxkVL/2gAMAwEAAhEDEQA/AOvw2MFtZNVxS2M59HIitVM6nwI43cy3iXUykyxGcxC0tmWhQAjSsQtEJj6ZDCEAYX4w2vYCR1pEX1sAWPZu85LTwtRuIUdmptx1iVlmfY8xTARVdeJHnLFPZ4t1iWPafnLCYVBuUSmuoXof4fsoNl4fKIW7D5GapWLE/IYywoxy/wDKfIw9IO7wM2I00weEPyGT8MmSHB3GOtL1TBo29R37pA+zyPUcjsOojT1C9iPD9ESreXcJh7kafCUxnT1l094ajx5To9lZWUEEH5+Um8y1tCrE29D6GDGmktphwP8AaWUSOtMVZWzZGBaI1pWjlSPtCVt7NEwkIBFtCEUcJRx1O4MvSOstwY8vTKss7k4a0jaPa8ayztHJQ28LxQIhWANi2iWhEoqznq+rfVuHdFqlK2yZl09IaX1ygXbly75YoYAnVz4cJfo0QgsBw/D3ySYsmbu8GmcankYlJVFgN0kXSJCUN7LNhHRLRYAJaFosIANtCOiWkbAWNMItoAJIzS1zA5W4MN/jzkkUyQLeF2wyELUFx74+o+02qdQMAVIIO4iczGo7oc1M2PFfZb801iOS6cn2dXeMauo4znqW1M6m+jDeDvEY9Ux5xbJeT6OjGIXnHK4M5lHI1vL9DF2k3h14IWRmyYj7pUGMFt95A2PlahjVS0csDHRAscBOumcojtCSEdkicEkKN7adw5/GQ60gmdvRGKZc5R6vtHXxUfeatOmFAVRYCFGkFAAElImDJkdM1xKlCR0bGVHI3C54DmZUWLnwPiiRU6hOhFjxB0MfeQQ1ofCRJUuSORtJAYckCwhCABCEIEBCEIAEIQgSEaYpMBACCvSvqNGG4/QyChXvcHRhvH5wl20rYugSMy+su7t7DLYvTJ2OLRyvb85yClUDKCOMmUTS9NEonWr8P6QLn53glM2/PznEKfndvlekSyitMx5omdAmAWTDALyjPqEjIsNM5aqMoJPAR2Ap6FyNW8wOUvbZoKGRAN5u3LKPuYwSu83ctIsjH2+RSYhMWJKCwZVqBVLHhNPZGFsgdx1mF/7oPATBxdQNUpodzOoItvvw8gZ199NNwAH2itl0SV8ZhkcHOACBcNxHaDOCwHSim1V6TG1mKo53NY215TQ/aD0lFCn6FG/ePobeyNCSZ5AJCeixwmj25U62YHeNfpJhOX6CYl3w/WYnK2UX5CdRGRnqdMdCEIChCEIAEIQgARsdGmAEDVCxyruB1P0ky6afOMwdAvcUxYAkFjoL8e+WsZs5UouzsSQjHlw5Qb0PMNlcVlva4J7CI6eUdG9sPSrqWYlGNmv28e+erAyE9hUaKRp5H/lc+Tf1m1hsFcXmdiKeZSONtO+a2D2ipRTuNrEdo0PxlqqvCF2kWlwigWkFREG+RYjaQsQJk18UTLIxU/JXeZejohX7bS1Se8xc0tJiciseABPlKqlGiXoy8S+eq730HUXuG/4kxBI6K2Hx8TvkkQSnsLxLwiOND3GAutnIdLtoNRfDOu/O9Q9tuqB5X85ax37S1NO1NDnI9q1lvv790yP2iL18Mv8A2eziwM5HE07Ed0qb5N+OH29wYzFvVcu7FnY3JP05CQRJdwlDqljyNpDekPGOrekd1+z0/wBnb++fkJ1k5foClsMe12+H4J1EtXhGHKtU0LFtARZJUNtFEWEAEMbFhAAtI6j5VJPAE+Ummdt+rkw9VuSG3edPrBjT5Nvo3XD4ZHFutc/Ezmf2jdIxTpnDobu46xHsr29s4rY/TTEYeiaKhSPZJvdb75gYnENUdnclmY3JP5p3RGa5n7I0axB7R857VgHui3321+nwnihE9qwi2uOxT5qD9YSJlXBZmWSUqOt9D1x9ZqTM2n1XRueZT4gGX4mlRjpfqxzMY2ITFUzpGTZ0DUyJDj3tTYc7DzNo6ljb7xGbRdSi9rr9/pMFS0bZySyAbhC8UiF5SxmwURH3HuMcIjSCF5OL/aBT6+FbnSt5WnK4miGHbzncdL6RehTFmz0WZd18ym9iOz7TlBhnPsN5Htma01W0d3o3DjVMyaWDPHh8ZfUcJapbOqseqjeVprYPotUYjOcg8z+faLqqaL+/DiT5N3ohTC4ZO0s3m025Dg8OKaKg3KLCTWmuVweeyV3W2hQYsbaKIFYsIhiAwAdCNjoAExelv/S1BzAHmwm1MnpMP7M/+H/UPtIrwWY0naR5Ri6WW1pXRSTbjNfEIHFvzyjKGFC67zM/fxydx9G2+PBWbC6oN5ZgPl957InrP2EL/lUD6TzTY+F9JiaCHdnDHuWxPynpOFJK5j7TMfMmW43tbMPWwofaiaUdqjqA8nU/HWXpXx63Q96/OWp6ezmtbK/ooCiZ1IwqWGgkbU0HATWs+/RnrFryzEvIMU2qdjr8mjw0q45iFDcnU/Ej6yy5/ViQ9UjUgY2m1xfnHGYDa/AK3CLeQVaWbUEg8x8u2U0x7glWUGxIuNPGQ3ryTMVT4NAjmI1aS8hKg2ivEEeFxJkxiG3WGvhFVSyx48k+mTqoHAR0YHU7iPMR4PbG4Eav2IY68S0S0EL2sWOiARJIot420SqhINiQeYiU72F9TzkASGAMCJDlbNvGW3iYATyvj8MKqMh0DC15OIknQybXKOGxnRiqnq2cdm/ymTUwVRPWRh4GeoARGpg7wJVWFM6OL/I5JWnycZ0PpBS9Y2zKuRBxLNvPlOxppYAcgBGLhkBuFF+6SxpntWjNnz/LXcKJXxo6h71+cnkOKW4C8SygecfRl9GjWxLSm9UmS1t0qkzVEoyXT2Qyvj1vTfu+Rv8ASTiDDQiaKW0RPkbsqvmQDkBy5S/OewdQo9vdNj3cJ0InOrybEEysemV7+8B5ia1pWx1HMhtvGo74lrcmjp8nbaM0iNZRygraX/O2KDMbbTO/Lm0N9GOUT0Y4XHjJYSO9g8MP0MBYbnbz+8Vajjc58Y60JKtiPp4focmLqDip7xaOG0XHsA9xkcSSstIrrosb9FpNpj2lZe3fLlKqrC6kEdkyCIxVKm6HKfge8S2c32ZsvQLW5N8GMNQDUkDvmUMbUIsQAee/4SFlLG7Ek9sZ5ZRmnorp6fBqtjE98QXHU/fEysg5CGUbrCL8xoX+O/s2FxSHc6+YkgcHiJxe0dj73p3B925AMw6eJqLudgb8zppGWYrroK+z1GE85wWNxLsER2JOm/d2kndOzw2z3AGeq5PHcBLJruMmXC4emagIkDv10HIlvIQoYcINL3O8k3JjaC5nZ/dsg+Zjytsz29Iu13DX7Zn4nEBdLEngBLbCYNSoXdjyPyluW+ydozSu5mhiq6IuZiAB8ZzeP28zXVBlHvcfCZmMxj1mzMeOg4Dum3sbYZNnqCw3hTx75mydXVPtk6+Ho4hd1+foz9nCoGLtcqbXYzq9n4q/UO/h3SdqSlSttCLWmMUNNyp/wnmOEIb1plObW9rhHQwMhwtYOt+PHvkr1AASdwF/KWFP+jMpYVWrPxVRYjhmOvykeKw3o2uPUbeORl3ZqHLmI1clz47vzsk9emHUqeP4JVcpo04c9TS5MkRZFTY2sd40PhpJZjpaZ38dd07QQhCQOESLEggFhEhJAIt4kIAELQiwASc5trAddSg1fgOemvxE6Jm4DUncOJlvB4OxDvq3D+WWY5dMx9TnmJ/sr7B2QKKXbVyNezkJsQhNmtHDyZHb2xrtYX/L8Jo4PZmVADv3nvOpmHVr3qog3BlLeegnYg6Re7XgXtVIxdoqlJC7mw4cye6cjTqi5I1BvrL3S/GZ6uQHqpv5ZjzmJSqgAgndFy06nkq7UvBbwWwXpuG6rgbhxvbfrym0cVb1kZfC4+EumJBY5nwa6y1XLIErodzD6+Up47LUBRRmYe1wU98vVKCtvAkKYPJ6jWHI6i8S1SX6hNJ/yMmhVek1nFjuvrY+M0atb0oyJxtmPIcRfnDEYV3GViuXjYG/HnulzD0VRcqiw/N/OPiqmv2XJXUpPaHgW0kTrU4FfK8mhLGhUYtfAVQzOLG5uQOPPTvvIErgGzDKe3SdEZXxGERxZh48ZXWOWbMPVVj4fKMwGLeD4XIchuAfVbhfkRw4R74V1G4N3aH4zPWGkdHH1k0ueBkSBuN6sPAn5RpqD/fSI4aNE5YfsdFjPSDmPOAqCGmT8sfY+0IgudysfAx6YV29nL3/AGEZRTYldRjnyxhYCCKz6KPE7v6y5S2ct7t1u/d5S4qAbhLZw/ZhzddxqSDCYNUHNjvMswhL0lJzLure2EixNcIpZjYAeZ4CLVrKouzAW33MqPSFf1r5B6ovYnt7obXoVTso4WoVIfecwfz3T0Kmcyg8wD5zh32Vp1GI790Y21MTSADE2AtfeDKoh7eyZfb5MvbpP6ipx65H55GZ9LEKrHML/n+0tYmoHJYnUm514n8+UzXU30F4+SfRXw2ehkxLwiRhtixI4CJAnuCEUxLQIbAGF4lo+TsBsW0S8dDYEdRAwykXBlCg9RbqQGymwO424GaMqsP3pt7i/Npn6jI4naLcSVVpifqjxRvmIpxSHeD/AJZOG0hkJ4TnLrq9o1fF9Mq/qqXZ5f0jhiqfAgeEurhCeA8ZMmAXjLF1z+iPif2UP1ae8IgxicDfwM2Vw6jcBH5ByEb87+iPh/sxRXvuDHwjxnO5G8bTYyxLRX1teiVgXszFwtQ+6O/WOXZzH1nPhp4TStC0qrq7fsZYpRUGzadrZb356/OZ9IFGZG3qdDzXgfzlNuZ21adsrj2TY9x/rG6fPSr9iMkJzwMEawBi3haddfZhMfH7CR+snVb4TFxFE0gVdfGdlI69JXBVhcGNshpEkUCAixSAhCECRCIkdEMAEtEvH3jLQASOgBHWgAxmAFybWkuAoXBdhqx07AN0q4oeoObqD53+k2lE5/W3x2mvBHsQUxyEUJHG8LzmOTUgyxAIsRjDTQC2hAGDd8nTALQtBTAtIAIRCbxVgAjRHUMLHcdD4ySMIgnyDRiUGtdTvUlT9DJyYYtMtQHg4+K6/KJO90990I5+RdtMIlosUCXIqEjpDTrq243kl5BGx0I28LwAdEMS8UmBIsa+oIva43jfGPVC7yBKlfaSKCQCxAJAHG2th5QJRwm16lRkpsrY1k/UKis70srMrshyWsc91YDMLc5exG3Dh6WIu+JNYBaaJWam2VmUtnXICBlTrXPIDjMzauEeoFdUNFfSKQgZ2YZiWNRxmsNTewAtc63mpsypVph8uGFV2ZesrZg9kZQ5zklbKSN59a0TfJq4HIMXRTDJTxNJ1d6aUx6O/r658xbrAAk+U7rF7UGFpI2ILOxKqzU6bG72JLZFvZeqe7QTiNmbLxWGdK/o0rBM+XDBiPQ5zcmm5NmNrjXdewnbf8bREWpVVqQIBIdlUrxsTe1xrMWfVUuNothaOS6HY5sRhjQp16lGqKlSp6Q084yZvVDP1faGm8Wl/o2cZiKFRlxh/jMtKs1JGz00urNkGgBbdqfVmX0Xxgq4GrhkapTZmqE1gt1UPU9VWJALFSRob6kyzslcSorYRMVkFD9OEqDDpZbozOhS9tcyak8DJc+fC5JXBc6LUK9WtWatiq1T9PXakqjKiPZRcuijUEMerfS0j/aF0hprQrYVWb0rBFsFYrZypbrWtfLfS8o9E8PiPTV2OMsqYr96ppL+/Iylje90zDSw3WvNvbrpXxeDoAghHbEvqPYXKl+fXb4GI0vlTfon0TbK21h8UjYbDVXR0pCzZHUoBlQMMwtcXGnYZS2jsirQptVq7UrqqC5JRPADmSdAOZjVx7/rsZXSk1b0NOhhkRSAWLEu+UnTqk6iZ3SPbNeo+FD4CqoXEK4V2VhVYK1kA3X1vrykqGr/AF8PkPR0XQqniDQL4h3Y1GzU1e2dafsZ7aBj61u3wHRmY2xtr1qzlamFqUAFuHdlYMbgZRbjrfwmyDMWffe2xpGmAEUxZUSEaYXjpAGdtVbJm9whvAb/AJyC8066BlKnUEEEdh3zHw3q2O9bqe8Ej6TqdBfDkydRPsltFESOnRZlObRyNRJ6eOccb98eNj4jkp8Yo2PX91fOVfPj+yVgteiddpDiIv8AxJeRkabErHflHnLFPo/77/5QBErqsaGWG2Vn2pyAjKVetUNkHjawHjNqjsaktjYsf5jf4TRSmBu07pmvrkv4oujp/wD0zJw2xhvqnOeVyFHcPvEr9H0PqEp2XuPIzYg6XBHMEaGx1Ft8x/kW63s0/FKWjz/aXRfDU8XhqbUhU/UvXNRnLhiUQPdSrALqTwMo7Z6OUaeOSlQwS1lbDsxo+kands9s+dibW0Fr8Z1B6DYUkMWxBIvlJrvdbixsb6XED0HwubOWxGa1s3p6ma3LNe9prnqI9tkdpjYDo0j1FWpsdaaEnM/6ovlFiQcgIJuQBpznbYzZtKtkWrTVwjBlVwCAbWBsdDobTF/5Mw3v4n/2Kn3l/EbCptRShnrKiG4ZarK59bRn3sOsd/IcpVeSHSabGSOU2PhUfZNZXb0aq9cq98uRkqZkII5MBoO4SXopiq9XD16tN6RxlWsGdKoZVQBVVVKjrWyqSD2jkZ0A6MYb0VOhlY06blwhdirsTe7+9qb/ANJNtXo9hsQQ1SmMwAAdSUewtYXUgncI/wCRHKfshyzD6P7J2hRqu1QYU061U1a2U1C4JW1kuAALgb775L06oYdaIco3pwwXD+j6tQu1gACBquuoII8TLlHonRVlYVMR1WDAHEVCpsb2IJ1Gm6Xn2PSbEDEsC1QLkTMxKoLm5RTorEad0reaO9Vv/iJS40cr0RoNRd8JiaZ9KzNVFVbkOxUFwzKNGFxv5dovo9JsNlq4EKzC+K4m9uo1iLzepgemce8inlxI+kzsL0VoJUSqXru1MlkFSqzqpIIuFbjrIWaXXc+CdM0zSqcHFu1QflEL1l3qrDs0PxlqFpldEopjH29ZHXwuPMSxTxSN6rA/PyMlyyu+ERjcrrzGh84JpgWbwlP9K6+o57m6wjDjGT10IHvL1h8IAXzMZxlquOBs4HwP52zVpV1cXUg9xlDaaWZG7Sp8d00dLXbZXlnciQjRHTtnONGluEcYQnCOoCwMSESiELAQhKyR8IQghgEIQgQEbCEECBYQhB+SWBjYQgiCqP43/j/+1ls/SEJLAFj4QigNMVYsIAEieEJIHP4H+JNTaX8P/Gn+qEJfh/miL/iQjjFhCdw5bP/Z
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cache.openshifttest
          resources:
          - samples
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cache.openshifttest
          resources:
          - samples/finalizers
          verbs:
          - update
        - apiGroups:
          - cache.openshifttest
          resources:
          - samples/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: sample-operator-controller-manager
      deployments:
      - name: sample-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/openshifttest/sample-operator:0.1.3
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: sample-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: sample-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sample
  links:
  - name: Sample Operator
    url: https://sample-operator.domain
  maturity: alpha
  provider:
    name: Liangquan Li
    url: https://github.com/LiangquanLi930/sample-operator
  version: 0.1.4
  replaces: sample-operator.v0.1.3
